init_dict = {
             'equal_ROIs_for each_image': True,
             'useCentralCropping': True,
             'crop_percentage': 38,
             'useTruncation': False,
             'trunc_percentage': 1,
             'multipleFiles': True,
             'useFitting': False,
             'fitting_order': 2,
             'image_height_in_mm': 'undefined',
             'image_width_in_mm': 'undefined',
             'pixel_size_mm': 0.781,
             'extensions': ['.tif', '.dcm', '.png', '.jpg'],
             'start_freq_range': 0,
             'end_freq_range': 20,
             'step': 0.01,
             'main_window_width': 512,
             'main_window_heigth': 512,
             'list_of_indices_raw': [(0x0040, 0x0275, 0x0032, 0x1060),
                                     (0x7005, 0x100a),
                                     (0x0905, 0x1030),
                                     ],
             'main_window_width_md': 350,
             'main_window_height_md': 400,
             'left_upper_corner_x_md': 30,
             'left_upper_corner_y_md': 30,
             'destroy_main_window': True,
             'first_data_set': False
}